Output demo.gif
Set FontFamily "FiraMono Nerd Font Medium"
Set FontSize 20
Set Theme "Catppuccin Frappe"
Set Height 1000
Set TypingSpeed 150ms
Set PlaybackSpeed 1.0


Sleep 500ms
Type "jarvish"
Enter
Sleep 500ms
Type "ls"
Enter
Sleep 1s
Type "jarvis, what option should I use to show hidden files?"
Enter
Sleep 3s
Type "ls -la "
Sleep 1s
Type '> ai "what is the most '
Sleep 500ms
Type 'heavy file?"'
Enter
Sleep 6.5s
Type "exit"
Enter
Sleep 1s

